# Generated by Django 6.0.2 on 2026-02-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seoarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoarticle',
            name='body',
            field=models.TextField(blank=True, help_text='Full article content (Markdown)'),
        ),
    ]
