'use client';

import { useState, useCallback } from 'react';

const RECORD_TYPES = ['A', 'AAAA', 'MX', 'NS', 'TXT', 'CNAME', 'SOA', 'CAA', 'SRV', 'PTR'];

const TYPE_LABELS = {
  A: 'A (IPv4)',
  AAAA: 'AAAA (IPv6)',
  MX: 'MX (Mail)',
  NS: 'NS (Nameservers)',
  TXT: 'TXT (Text)',
  CNAME: 'CNAME (Alias)',
  SOA: 'SOA (Authority)',
  CAA: 'CAA (Cert Auth)',
  SRV: 'SRV (Service)',
  PTR: 'PTR (Pointer)',
};

function cleanDomain(input) {
  let d = input.trim().toLowerCase();
  d = d.replace(/^https?:\/\//, '').replace(/\/.*$/, '').replace(/^www\./, '');
  return d;
}

async function queryDns(domain, type) {
  try {
    const res = await fetch(`https://dns.google/resolve?name=${encodeURIComponent(domain)}&type=${type}`);
    const data = await res.json();
    if (data.Answer) {
      return data.Answer.map(a => ({
        name: a.name,
        ttl: a.TTL,
        type: type,
        data: a.data,
      }));
    }
    return [];
  } catch {
    return [];
  }
}

function recordToBind(record) {
  const name = record.name.endsWith('.') ? record.name : record.name + '.';
  return `${name}\t${record.ttl}\tIN\t${record.type}\t${record.data}`;
}

function generateZoneFile(domain, allRecords, timestamp) {
  const lines = [];
  lines.push(`;; DNS Zone File Export for ${domain}`);
  lines.push(`;; Generated by DomyDomains DNS Export Tool`);
  lines.push(`;; Date: ${timestamp}`);
  lines.push(`;; Source: Google Public DNS (dns.google)`);
  lines.push(';;');
  lines.push(`;; BIND Zone File Format`);
  lines.push('');
  lines.push(`$ORIGIN ${domain}.`);
  lines.push('');

  for (const type of RECORD_TYPES) {
    const records = allRecords[type] || [];
    if (records.length > 0) {
      lines.push(`; ${type} Records`);
      for (const r of records) {
        lines.push(recordToBind(r));
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

function generateCsv(allRecords) {
  const lines = ['Name,TTL,Class,Type,Data'];
  for (const type of RECORD_TYPES) {
    const records = allRecords[type] || [];
    for (const r of records) {
      const name = r.name.endsWith('.') ? r.name : r.name + '.';
      const escaped = r.data.includes(',') ? `"${r.data}"` : r.data;
      lines.push(`${name},${r.ttl},IN,${r.type},${escaped}`);
    }
  }
  return lines.join('\n');
}

function generateJson(domain, allRecords, timestamp) {
  const output = {
    domain,
    exportDate: timestamp,
    source: 'dns.google',
    records: {},
  };
  for (const type of RECORD_TYPES) {
    const records = allRecords[type] || [];
    if (records.length > 0) {
      output.records[type] = records.map(r => ({
        name: r.name,
        ttl: r.ttl,
        class: 'IN',
        type: r.type,
        data: r.data,
      }));
    }
  }
  return JSON.stringify(output, null, 2);
}

function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

const inputStyle = {
  flex: 1,
  padding: '14px 16px',
  borderRadius: '10px',
  border: '1px solid #2a2a2a',
  background: '#0a0a0a',
  color: '#fff',
  fontSize: '1rem',
  outline: 'none',
  minWidth: 0,
};

const btnStyle = {
  padding: '14px 32px',
  borderRadius: '10px',
  border: 'none',
  background: '#8b5cf6',
  color: '#fff',
  fontSize: '1rem',
  fontWeight: 700,
  cursor: 'pointer',
  whiteSpace: 'nowrap',
};

const downloadBtnStyle = {
  padding: '10px 20px',
  borderRadius: '8px',
  border: '1px solid #2a2a2a',
  background: '#0a0a0a',
  color: '#fff',
  fontSize: '0.85rem',
  fontWeight: 600,
  cursor: 'pointer',
  transition: 'all 0.2s',
};

export default function DnsExportTool() {
  const [domain, setDomain] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [results, setResults] = useState(null);
  const [copied, setCopied] = useState(false);
  const [selectedTypes, setSelectedTypes] = useState(new Set(RECORD_TYPES));
  const [exportFormat, setExportFormat] = useState('bind');

  const toggleType = (type) => {
    setSelectedTypes(prev => {
      const next = new Set(prev);
      if (next.has(type)) {
        if (next.size > 1) next.delete(type);
      } else {
        next.add(type);
      }
      return next;
    });
  };

  const handleExport = useCallback(async () => {
    const d = cleanDomain(domain);
    if (!d || !d.includes('.')) {
      setError('Please enter a valid domain name (e.g., example.com).');
      return;
    }

    setError('');
    setLoading(true);
    setResults(null);
    setCopied(false);

    try {
      const allRecords = {};
      let totalRecords = 0;

      const promises = [...selectedTypes].map(async (type) => {
        const records = await queryDns(d, type);
        allRecords[type] = records;
        totalRecords += records.length;
      });

      await Promise.all(promises);

      if (totalRecords === 0) {
        setError(`No DNS records found for ${d}. Check the domain name and try again.`);
        setLoading(false);
        return;
      }

      const timestamp = new Date().toISOString();
      const zoneFile = generateZoneFile(d, allRecords, timestamp);

      setResults({
        domain: d,
        allRecords,
        totalRecords,
        zoneFile,
        timestamp,
        typeCounts: Object.fromEntries(
          RECORD_TYPES.map(t => [t, (allRecords[t] || []).length])
        ),
      });
    } catch {
      setError('Failed to fetch DNS records. Please check the domain and try again.');
    } finally {
      setLoading(false);
    }
  }, [domain, selectedTypes]);

  const handleDownload = () => {
    if (!results) return;
    const { domain: d, allRecords, timestamp } = results;

    if (exportFormat === 'bind') {
      const content = generateZoneFile(d, allRecords, timestamp);
      downloadFile(content, `${d}-dns-records.zone`, 'text/plain');
    } else if (exportFormat === 'csv') {
      const content = generateCsv(allRecords);
      downloadFile(content, `${d}-dns-records.csv`, 'text/csv');
    } else if (exportFormat === 'json') {
      const content = generateJson(d, allRecords, timestamp);
      downloadFile(content, `${d}-dns-records.json`, 'application/json');
    }
  };

  const handleCopy = () => {
    if (!results) return;
    const { domain: d, allRecords, timestamp } = results;

    let content;
    if (exportFormat === 'bind') {
      content = generateZoneFile(d, allRecords, timestamp);
    } else if (exportFormat === 'csv') {
      content = generateCsv(allRecords);
    } else {
      content = generateJson(d, allRecords, timestamp);
    }

    navigator.clipboard.writeText(content).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div style={{ marginBottom: '48px' }}>
      {/* Input */}
      <div style={{
        background: '#111',
        border: '1px solid #1e1e1e',
        borderRadius: '16px',
        padding: '32px',
        marginBottom: '24px',
      }}>
        <label style={{ display: 'block', fontSize: '0.85rem', color: '#9ca3af', marginBottom: '8px', fontWeight: 600 }}>
          Domain Name
        </label>
        <div style={{ display: 'flex', gap: '12px', marginBottom: '20px' }}>
          <input
            type="text"
            placeholder="example.com"
            value={domain}
            onChange={e => setDomain(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && handleExport()}
            style={inputStyle}
          />
          <button
            onClick={handleExport}
            disabled={loading}
            style={{ ...btnStyle, opacity: loading ? 0.6 : 1 }}
          >
            {loading ? 'Fetching...' : 'Export DNS'}
          </button>
        </div>

        {/* Record type filter */}
        <label style={{ display: 'block', fontSize: '0.85rem', color: '#9ca3af', marginBottom: '8px', fontWeight: 600 }}>
          Record Types to Export
        </label>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px', marginBottom: '20px' }}>
          {RECORD_TYPES.map(type => (
            <button
              key={type}
              onClick={() => toggleType(type)}
              style={{
                padding: '6px 14px',
                borderRadius: '8px',
                border: `1px solid ${selectedTypes.has(type) ? '#8b5cf6' : '#2a2a2a'}`,
                background: selectedTypes.has(type) ? '#8b5cf622' : '#0a0a0a',
                color: selectedTypes.has(type) ? '#8b5cf6' : '#666',
                fontSize: '0.8rem',
                fontWeight: 600,
                cursor: 'pointer',
                transition: 'all 0.2s',
              }}
            >
              {type}
            </button>
          ))}
        </div>

        {/* Export format */}
        <label style={{ display: 'block', fontSize: '0.85rem', color: '#9ca3af', marginBottom: '8px', fontWeight: 600 }}>
          Export Format
        </label>
        <div style={{ display: 'flex', gap: '8px' }}>
          {[
            { id: 'bind', label: 'BIND Zone File', icon: '📄' },
            { id: 'csv', label: 'CSV', icon: '📊' },
            { id: 'json', label: 'JSON', icon: '{ }' },
          ].map(fmt => (
            <button
              key={fmt.id}
              onClick={() => setExportFormat(fmt.id)}
              style={{
                padding: '8px 16px',
                borderRadius: '8px',
                border: `1px solid ${exportFormat === fmt.id ? '#8b5cf6' : '#2a2a2a'}`,
                background: exportFormat === fmt.id ? '#8b5cf622' : '#0a0a0a',
                color: exportFormat === fmt.id ? '#8b5cf6' : '#666',
                fontSize: '0.8rem',
                fontWeight: 600,
                cursor: 'pointer',
                transition: 'all 0.2s',
              }}
            >
              {fmt.icon} {fmt.label}
            </button>
          ))}
        </div>

        {error && (
          <p style={{ color: '#ef4444', marginTop: '12px', fontSize: '0.9rem' }}>{error}</p>
        )}
      </div>

      {/* Results */}
      {results && (
        <div>
          {/* Summary */}
          <div style={{
            background: '#111',
            border: '1px solid #1e1e1e',
            borderRadius: '16px',
            padding: '24px',
            marginBottom: '24px',
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', flexWrap: 'wrap', gap: '12px' }}>
              <div>
                <h3 style={{ margin: 0, fontWeight: 700, fontSize: '1.2rem' }}>
                  📋 DNS Records for {results.domain}
                </h3>
                <p style={{ margin: '4px 0 0', color: '#9ca3af', fontSize: '0.85rem' }}>
                  {results.totalRecords} record{results.totalRecords !== 1 ? 's' : ''} found across {Object.values(results.typeCounts).filter(c => c > 0).length} record types
                </p>
              </div>
              <div style={{ display: 'flex', gap: '8px' }}>
                <button onClick={handleCopy} style={downloadBtnStyle}>
                  {copied ? '✓ Copied!' : '📋 Copy'}
                </button>
                <button onClick={handleDownload} style={{ ...downloadBtnStyle, background: '#8b5cf6', border: '1px solid #8b5cf6' }}>
                  ⬇ Download {exportFormat === 'bind' ? '.zone' : exportFormat === 'csv' ? '.csv' : '.json'}
                </button>
              </div>
            </div>

            {/* Type breakdown */}
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
              {RECORD_TYPES.filter(t => results.typeCounts[t] > 0).map(type => (
                <div key={type} style={{
                  padding: '6px 14px',
                  borderRadius: '8px',
                  background: '#8b5cf612',
                  border: '1px solid #8b5cf633',
                  fontSize: '0.8rem',
                  fontWeight: 600,
                  color: '#8b5cf6',
                }}>
                  {type}: {results.typeCounts[type]}
                </div>
              ))}
            </div>
          </div>

          {/* Records table */}
          <div style={{
            background: '#111',
            border: '1px solid #1e1e1e',
            borderRadius: '16px',
            padding: '24px',
            marginBottom: '24px',
            overflowX: 'auto',
          }}>
            <h3 style={{ margin: '0 0 16px', fontWeight: 700, fontSize: '1rem' }}>Record Details</h3>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid #2a2a2a' }}>
                  {['Name', 'TTL', 'Class', 'Type', 'Data'].map(h => (
                    <th key={h} style={{
                      textAlign: 'left',
                      padding: '10px 12px',
                      color: '#9ca3af',
                      fontWeight: 600,
                      fontSize: '0.75rem',
                      textTransform: 'uppercase',
                      letterSpacing: '0.05em',
                    }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {RECORD_TYPES.filter(t => (results.allRecords[t] || []).length > 0).flatMap(type =>
                  results.allRecords[type].map((r, i) => (
                    <tr key={`${type}-${i}`} style={{ borderBottom: '1px solid #1a1a1a' }}>
                      <td style={{ padding: '8px 12px', fontFamily: 'monospace', color: '#ddd', whiteSpace: 'nowrap' }}>{r.name}</td>
                      <td style={{ padding: '8px 12px', color: '#9ca3af' }}>{r.ttl}s</td>
                      <td style={{ padding: '8px 12px', color: '#9ca3af' }}>IN</td>
                      <td style={{ padding: '8px 12px' }}>
                        <span style={{
                          display: 'inline-block',
                          padding: '2px 8px',
                          borderRadius: '4px',
                          background: '#8b5cf622',
                          color: '#8b5cf6',
                          fontSize: '0.75rem',
                          fontWeight: 700,
                        }}>{r.type}</span>
                      </td>
                      <td style={{ padding: '8px 12px', fontFamily: 'monospace', color: '#ddd', wordBreak: 'break-all', maxWidth: '400px' }}>{r.data}</td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>

          {/* Raw zone file preview */}
          <div style={{
            background: '#111',
            border: '1px solid #1e1e1e',
            borderRadius: '16px',
            padding: '24px',
            marginBottom: '24px',
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
              <h3 style={{ margin: 0, fontWeight: 700, fontSize: '1rem' }}>
                {exportFormat === 'bind' ? 'BIND Zone File Preview' : exportFormat === 'csv' ? 'CSV Preview' : 'JSON Preview'}
              </h3>
            </div>
            <pre style={{
              background: '#0a0a0a',
              border: '1px solid #2a2a2a',
              borderRadius: '10px',
              padding: '16px',
              overflow: 'auto',
              fontSize: '0.8rem',
              lineHeight: 1.6,
              color: '#ccc',
              maxHeight: '400px',
              margin: 0,
            }}>
              {exportFormat === 'bind'
                ? results.zoneFile
                : exportFormat === 'csv'
                  ? generateCsv(results.allRecords)
                  : generateJson(results.domain, results.allRecords, results.timestamp)}
            </pre>
          </div>
        </div>
      )}
    </div>
  );
}
